### ISSUE TITLE
Pie Chart Labels don't show up

### ISSUE THREAD

**Issue by Arun-Verma** [bloomberg/bqplot#73] opened 2015-12-09 17:25 UTC
The following code snippet doesn't print labels on the pie slices
"from bqplot import *
from IPython.display import display
pie = Pie(sizes=[], select_slices=True, opacities=[0.2])
pie_fig = Figure(marks=[pie])    
pie.sizes=[1,2,3]
pie.labels = ['A','B','C']

display(pie_fig)"

However, if next I change sizes  via pie.sizes=[1,2,4], labels show up!

**Comment by dmadeka** [comment] 2015-12-11 00:07
I was unable to recreate this error with the latest version of bqplot. Not sure what the issue is. Maybe you can update and try again.

**Comment by SylvainCorlay** [comment] 2015-12-11 01:12
This is actually fixed in master. Closing.

**Closed by SylvainCorlay** 2015-12-11 01:12 UTC
Labels: bug
