### ISSUE TITLE
Graph color and scale has changed since release of v0.12

### ISSUE THREAD

**Issue by jaladh-singhal** [bloomberg/bqplot#962] opened 2019-11-01 14:05 UTC
**Describe the bug**
Since the release of v0.12, I'm experiencing problems in the way graph of plots appear:
1. The color of grid which used to be kinda greyish-blue with white grid lines, is now plane white with grey grid lines.
2. The x-axis scale has also increased making graphs look horizontally stretched.

**To Reproduce**
By just plotting the basic line chart using pyplot API with default configurations, it can be observed on the 2 versions:
1. `bqplot v0.11.8`
![image](https://user-images.githubusercontent.com/36361463/68029623-a05e0900-fcdd-11e9-9149-414dd7efd46e.png)

2. `bqplot v0.12.0`
Plot for exact same code
![image](https://user-images.githubusercontent.com/36361463/68029344-072ef280-fcdd-11e9-8900-d201300ef1d8.png)

Also, in v0.12.0, some of the grid lines go unexpectedly missing for line charts like this:
![image](https://user-images.githubusercontent.com/36361463/68030438-79083b80-fcdf-11e9-9c07-0a5b5f2144a2.png)

**Environment**
 - Operating System and Version: Ubuntu 16.04
 - I am using a conda environment - in which everything is same just upgraded bqplot from v0.11.8 to v0.12.0

**Additional context**
I am not aware if this has been explicitly changed in this new version on bqplot (v0.12.0) since I couldn't find any changelog.

**Comment by aboulle** [comment] 2019-11-05 13:40
Exact same issue here. Both on ubuntu 18.04 and on a Binder instance of the notebook.
In addition:
1. the axes scale don't match the data range anymore (both in H and V direction).
2. Unusual behavior of the data extending out of the figure
3. This modification breaks the layout when using HBoxes and VBoxes. Example:
- v0.11.9
![0 11 2](https://user-images.githubusercontent.com/13114636/68213857-a1907e00-ffdc-11e9-81f4-ff5a69ddd526.png)

- v0.12
![0 12](https://user-images.githubusercontent.com/13114636/68213884-ad7c4000-ffdc-11e9-9015-99bccda09e8f.png)

Temporary workaround: fix the bqplot version in the requirements.txt or environment.yml file:
bqplot=0.11.2

**Comment by aboulle** [comment] 2019-11-05 14:14
Some information is given in this commit: https://github.com/bloomberg/bqplot/commit/28231a88796123d62327a1bf8891b98444ef8527

It may be obvious, but it is unclear to me how to update my Python code in order to restore the previous behavior.

**Comment by martinRenou** [comment] 2019-11-05 14:41
Thanks for filling this issue!

Concerning the colors, it is due to bqplot supporting JupyterLab CSS variables (allowing support for JupyterLab themes).

If you want to set the width to a lower value you can play with the `plot.layout.width` parameter.
For example: 
- `plot.layout.width = '50%'`, this will take 50% of the available space
- `plot.layout.width = '500px'`, this will take 500 pixels

The lines issue looks like an ugly bug... I will look into it. Thanks again

**Comment by martinRenou** [comment] 2019-11-05 14:42
More on the `layout` attribute here: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html

**Comment by martinRenou** [comment] 2019-11-05 15:22
> The lines issue looks like an ugly bug...

I cannot reproduce this issue 100% of the times, there seems to be a race condition somewhere.

But I found something that might be the origin of the issue for the lines not being long enough. The figure size is still hardcoded somewhere in the code: https://github.com/bloomberg/bqplot/blob/master/js/src/Figure.ts#L72

cc. @SylvainCorlay

**Comment by martinRenou** [comment] 2019-11-05 16:05
I opened a PR that will fix it #964. You can try my fix on binder: https://mybinder.org/v2/gh/martinRenou/bqplot/test_binder

**Comment by aboulle** [comment] 2019-11-06 14:35
Thanks for the effort (and thanks to all the team for this terrific library).
Here is another example of the weird axis/data behavior (taken from your binder. The file is examples/Advanced Plotting/Axis Properties.ipynb)

![Screenshot_2019-11-06 Axis Properties](https://user-images.githubusercontent.com/13114636/68307077-eda9f400-00aa-11ea-95ed-c250bbaedc76.png)

**Comment by martinRenou** [comment] 2019-11-06 15:00
Again something I can't seem to reproduce locally... I also see it on binder though

**Comment by martinRenou** [comment] 2019-11-07 14:54
So, after a quick debug session with @maartenbreddels, we found that the Axes and grid sizes are not properly linked to the figure size...

This should be fixed in #964. The binder seems to work now: https://mybinder.org/v2/gh/martinRenou/bqplot/test_binder

**Closed** 2019-11-08 13:42 UTC
