### ISSUE TITLE
tooltip on hover can't be removed

### ISSUE THREAD

**Issue by davidbrochart** [bloomberg/bqplot#896] opened 2019-08-28 12:14 UTC
**Describe the bug**
It looks like the tooltip-on-hover feature for scatter marks is always activated, even when we don't want it.

**To Reproduce**
With a notebook consisting of the following code:
```python
import numpy as np
from bqplot import pyplot as plt
import bqplot

n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n)*10).astype(int)

fig2 = plt.figure( title='Line Chart')
np.random.seed(0)
p = plt.scatter(x, y)
fig2.layout.width = 'auto'
fig2.layout.height = 'auto'
fig2.layout.min_height = '300px' # so it shows nicely in the notebook
fig2

p.interactions = {'click': 'select'}
p.selected_style = {'opacity': 1.0, 'fill': 'DarkOrange', 'stroke': 'Red'}
p.unselected_style = {'opacity': 0.5}
p.tooltip = bqplot.Tooltip(fields=['x', 'y'], formats=['', '.2f'])
```

We can see that the tooltip on hover works, even though we didn't specify it in the interactions. For it to work we should have:
```python
p.interactions = {'click': 'select', 'hover': 'tooltip'}
```

**Comment by martinRenou** [comment] 2019-09-19 11:04
Which bqplot version were you using?
I cannot reproduce this issue on master

**Comment by davidbrochart** [comment] 2019-09-19 12:52
I just tried with master, the tooltip on hover is activated. You don't see any tooltip on hover?

**Comment by martinRenou** [comment] 2019-09-19 12:58
Not if I don't execute `p.interactions = {'click': 'select', 'hover': 'tooltip'}`

**Comment by davidbrochart** [comment] 2019-09-19 13:00
That's strange, my version is `0.12.0a2`.

**Comment by martinRenou** [comment] 2019-09-19 13:04
Indeed.. Are you using JLab or the Classical Notebook?

**Comment by davidbrochart** [comment] 2019-09-19 13:07
The classic Notebook.
Actually it looks like this line activates the tooltip on hover:
`p.tooltip = bqplot.Tooltip(fields=['x', 'y'], formats=['', '.2f'])`
Even though we only have this (no tooltip on hover interaction):
`p.interactions = {'click': 'select'}`

**Comment by martinRenou** [comment] 2019-09-19 13:08
Oooh I see now. I was running all of this in a single cell:

Now I can reproduce the issue when running this in two separate cells:
```python
import numpy as np
from bqplot import pyplot as plt
import bqplot

n = 200
x = np.linspace(0.0, 10.0, n)
y = np.cumsum(np.random.randn(n)*10).astype(int)

fig2 = plt.figure( title='Line Chart')
np.random.seed(0)
p = plt.scatter(x, y)
fig2.layout.width = 'auto'
fig2.layout.height = 'auto'
fig2.layout.min_height = '300px' # so it shows nicely in the notebook
fig2
```

```python
p.interactions = {'click': 'select'}
p.selected_style = {'opacity': 1.0, 'fill': 'DarkOrange', 'stroke': 'Red'}
p.unselected_style = {'opacity': 0.5}
p.tooltip = bqplot.Tooltip(fields=['x', 'y'], formats=['', '.2f'])
```

Weird that the behavior is different when you run it in two separate cells. I'll investigate a bit on this.

**Comment by davidbrochart** [comment] 2019-09-19 13:13
Yes sorry I didn't format my example well.
That's a strange behavior indeed.

**Comment by martinRenou** [comment] 2019-09-20 12:21
Why are you assigning to `p.tooltip` if you don't want a tooltip for you scatter?

**Comment by davidbrochart** [comment] 2019-09-20 12:30
It was a mistake, I forgot to remove it. I thought that removing it from the interactions was enough.
But it's not a big deal to leave things like that.

**Comment by martinRenou** [comment] 2019-09-20 12:51
Right, sorry I'm still learning how bqplot works/should work.

Now I think I understand. If the `tooltip` is not bound to any mouse interaction it should never be displayed, is that it?

**Comment by davidbrochart** [comment] 2019-09-20 12:52
Yes, that's how I see it too.

**Comment by martinRenou** [comment] 2019-09-20 13:13
I found the issue. There is a collision in method names... The `reset_hover` method in `Mark.ts` which is supposed to be used for resetting the hover event is overridden by the `reset_hover` in `ScatterBase.ts` which is used for resetting the currently hovered points.

This results in the hover event to not be removed when doing `p.interactions = {'click': 'select'}`

**Comment by davidbrochart** [comment] 2019-09-20 13:16
Great, and is it fixable?

**Comment by martinRenou** [comment] 2019-09-20 13:18
Sure, PR coming :)

**Closed** 2019-09-20 15:04 UTC

**Comment by davidbrochart** [comment] 2019-09-20 15:06
Thanks!
