### ISSUE TITLE
Won't install on top of "docker-demo-image" (jupyter/demo on DockerHub) UnicodeDecodeError

### ISSUE THREAD

**Issue by mjbright** [bloomberg/bqplot#36] opened 2015-10-12 15:34 UTC
I've tried installing this on the Jupyter/demo image, but I get the following error.

The following is the end of the output log of a build built on top of the jupyter/demo image:

Any idea how to fix this?

If you need to test, my Dockerfile is at
     https://github.com/mjbright/jupyter_trusted_builds/blob/master/demo/Dockerfile
```
Step 31 : RUN pip install bqplot
Collecting bqplot
Downloading bqplot-0.3.8.tar.gz (451kB)
Requirement already satisfied (use --upgrade to upgrade): ipywidgets in /opt/conda/lib/python3.4/site-packages (from bqplot)
Requirement already satisfied (use --upgrade to upgrade): numpy in /opt/conda/lib/python3.4/site-packages (from bqplot)
Requirement already satisfied (use --upgrade to upgrade): pandas in /opt/conda/lib/python3.4/site-packages (from bqplot)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2 in /opt/conda/lib/python3.4/site-packages (from pandas->bqplot)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /opt/conda/lib/python3.4/site-packages (from pandas->bqplot)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /opt/conda/lib/python3.4/site-packages (from python-dateutil>=2->pandas->bqplot)
Building wheels for collected packages: bqplot
Running setup.py bdist_wheel for bqplot
Stored in directory: /home/jovyan/.cache/pip/wheels/e4/f9/62/512546616698b2ac0b48bf9042ce807cb914987993d592b453
Successfully built bqplot
Installing collected packages: bqplot
Successfully installed bqplot-0.3.8
---> 5c92ffed1fbe
```

```
Step 32 : RUN python -m bqplot.install --symlink --user --force
[91m/opt/conda/bin/python: Error while finding spec for 'bqplot.install' (<class 'UnicodeDecodeError'>: 'ascii' codec can't decode byte 0xc3 in position 98318: ordinal not in range(128))
```

**Comment by SylvainCorlay** [comment] 2015-10-13 02:17
@mjbright thanks for reporting. I am not experienced with docker, and I have not met this problem yet. Have you tried running the second step without the `--symlink` argument?

**Comment by mjbright** [comment] 2015-10-13 07:04
Thanks for the quick reply.

No that doesn't help at all I'm afraid.

For what it's worth I "accidentally" installed bqplot just now on a Ubuntu
14.04.2 LTS without problem.
I tried again within my Docker container but it fails ... and that is
running a "Debian GNU/Linux 8 (jessie)"

I'll ask about this on the Jupyter mailing list,
Regards,
Mike.

**Comment by SylvainCorlay** [comment] 2015-10-13 15:01
@jasongrout was saying earlier that it might be caused by a unicode character that would have slipped into one of the files, and issue that he encountered in Sage. Does inserting `# -*- coding: utf-8 -*-` at the top of `install.py` and `bqplot/__init__.py` help?

**Comment by fm75** [comment] 2016-04-26 14:39
Inserting # -*- coding: utf-8 -*- at the top of just bqplot/__init__.py  **after **the  pip install step does not help.

**Comment by fm75** [comment] 2016-04-26 15:20
In RHEL7, adding
`ENV LANG en_US.UTF-8` 
to the Dockerfile fixed this issue.
Without it all of the "locales" were "POSIX", even though the machine in which they were created were "en_US.UTF-8"

**Comment by SylvainCorlay** [comment] 2016-08-09 11:55
Closing since @fm75 fixed the issue.

**Closed by SylvainCorlay** 2016-08-09 11:55 UTC
Labels: bug
