### ISSUE TITLE
Scatter example 'unhovered' style not applied first

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#378] opened 2016-12-06 03:53 UTC
In scatter plot mark example, the “Adding tooltip and custom hover style” example - the initial drawing has opacity 1, but after a single hover, opacity goes to the unhovered style of opacity 0.5.

**Comment by ssunkara1** [comment] 2017-01-27 14:47
This is not a bug. When we do not hover on anything, both `hovered_style` and `unhovered_style` should not apply. Just like, when `selected` is `None`, which means we are not even trying to select, `unselected_style` is not applied.

**Comment by jasongrout** [comment] 2017-01-27 15:15
So the opacity should go back to 1 after I stop hovering?

**Comment by ssunkara1** [comment] 2017-01-27 16:02
I would have expected it to. But it doesn't as of now. So we'll keep this open till that is fixed.

**Comment by ssunkara1** [comment] 2017-02-05 18:11
This is fixed in #425

**Closed by ssunkara1** 2017-02-05 18:11 UTC
Labels: bug
