### ISSUE TITLE
notebook div references

### ISSUE THREAD

**Issue by jasongrout** [bloomberg/bqplot#372] opened 2016-12-02 23:19 UTC
These two references to the `#notebook` div will probably fail miserably in JLab:

https://github.com/bloomberg/bqplot/blob/d3f4e4f1f51311fc2016db9c2af22568be33ab27/js/src/Mark.js#L250

https://github.com/bloomberg/bqplot/blob/3dd09694fce17841787bcb0a26b21079d62ee167/js/src/MarketMap.js#L604

We should figure out a way to do whatever it is they are doing without hacking the global structure of the DOM.

**Comment by dmadeka** [comment] 2016-12-06 05:53
This is a duplicate of #382

**Closed by dmadeka** 2016-12-06 05:53 UTC

**Comment by jasongrout** [comment] 2016-12-06 15:32
Thanks! I should have checked to see if I opened the issue already.
