### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 98318: ordinal not in range(128)

### ISSUE THREAD

**Issue by elenocastro** [bloomberg/bqplot#283] opened 2016-08-17 05:50 UTC
I am new in Python, and I think that is something wrong when I try to import something from bqplot. I will appreciate your help.

**Comment by SylvainCorlay** [comment] 2016-08-17 09:00
@elenocastro are you running bqplot in a docker instance? 

Issue https://github.com/bloomberg/bqplot/issues/36 was similar in the context of a docker instance.

@fm75 had a fix for this.

**Comment by elenocastro** [comment] 2016-08-18 21:19
Sorry I am new, what to do you mean by docker instance?
I am using Jupyter

**Comment by SylvainCorlay** [comment] 2016-08-18 21:25
Thanks, can you provide some details about how you installed jupyter and bqplot. (OS / python distribution) Are you using anaconda?

I am really curious about this because it is the second time someone reports something like this and I could never reproduce.

**Comment by elenocastro** [comment] 2016-08-18 21:57
I installed anaconda for my mac OS X, and then I try to install bqplot using pip. At the end of the output, appears: 
File "//anaconda/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 98318: ordinal not in range(128)

**Comment by fm75** [comment] 2016-08-18 22:13
I think perhaps closing my issue was wrong. I fixed it by altering the environment of a docker container. After that alteration, the install succeeded.

I suspect that the issue is that some file in bqplot has a UTF-8 character in the source.
98,318 bytes into some text.

**Comment by nnashok** [comment] 2016-08-29 18:59
I see the same problem in the context of running Jupyter in a docker container.

**Comment by fm75** [comment] 2016-08-29 23:36
For the docker issue, have you tried what I did to solve the problem in issue 36?

**Comment by nnashok** [comment] 2016-08-30 02:44
@fm75 , I did and it worked, thanks :)

**Comment by SylvainCorlay** [comment] 2016-09-05 12:24
Should be fixed with #311 .

**Closed by SylvainCorlay** 2016-09-05 12:24 UTC
