### ISSUE TITLE
0.12.0-alpha.1 - Tooltips do not appear

### ISSUE THREAD

**Issue by kaiayoung** [bloomberg/bqplot#874] opened 2019-06-24 17:46 UTC
Tooltips do not seem to appear in 0.12.0-alpha.1, though they appeared in 0.12.0-alpha.0 (they were solid black, however). See the below code to reproduce in JLab:

```
from bqplot import *
x_scale = OrdinalScale()
y_scale = LinearScale()

bar = Bars(x=[1,2,3],
           y=[1,2,3],
           scales={'x': x_scale, 'y': y_scale},
           tooltip=Tooltip(fields=['x', 'y']))
ax_x = Axis(scale=x_scale)
ax_y = Axis(scale=y_scale, orientation='vertical')

Figure(marks=[bar], axes=[ax_x, ax_y])
```

**Comment by martinRenou** [comment] 2019-09-16 11:21
This seems to work on master, doesn't it?
![Screenshot from 2019-09-16 13-19-25](https://user-images.githubusercontent.com/21197331/64954085-d3ab1c80-d884-11e9-860e-ee5161c38872.png)

**Comment by JohanMabille** [comment] 2019-09-18 11:21
I could not reproduce this issue neither. @kaiayoung do you still have the issue?

**Comment by kaiayoung** [comment] 2019-09-19 14:32
It seems to work when you point binder to master! This may have been fixed in #855 after this issue was posted.

**Comment by martinRenou** [comment] 2020-01-14 08:13
I think this issue is ready to be closed.

**Comment by martinRenou** [comment] 2020-01-17 11:08
@ibdafna

**Comment by ibdafna** [comment] 2020-01-17 15:47
Closing as per the comments above

**Closed** 2020-01-17 15:47 UTC

**Comment by martinRenou** [comment] 2020-01-17 16:10
Thanks! And sorry for all the notifications
